# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-14 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HK_JYS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_hk', models.TimeField()),
                ('data1', models.IntegerField()),
                ('data2', models.IntegerField()),
                ('data3', models.CharField(max_length=4)),
                ('save_date', models.DateTimeField(default=1473876121.562062)),
            ],
            options={
                'db_table': 'J03_01_C_T60',
                'verbose_name': '\u9999\u6e2f\u4ea4\u6613\u6240',
                'indexes': [],
            },
        ),
    ]
